name: aurora
channels:
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cffi=1.17.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - ffmpeg=4.3.2
  - freetype=2.12.1
  - future=1.0.0
  - gmp=6.3.0
  - gnutls=3.6.13
  - icu=75.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libpng=1.6.43
  - libprotobuf=3.19.6
  - libsqlite=3.46.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.0
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=21.1.5
  - magma=2.5.4
  - mkl=2021.4.0
  - nccl=2.27.3.1
  - ncurses=6.5
  - nettle=3.6
  - ninja=1.13.1
  - numpy=1.24.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.6.0
  - pillow=9.4.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - python=3.8.19
  - python_abi=3.8
  - readline=8.2
  - setuptools=75.3.0
  - sleef=3.9.0
  - tbb=2021.7.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - x264=1!161.3030
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.13.1
      - fire==0.7.1
      - fonttools==4.57.0
      - fsspec==2024.6.1
      - grad-cam==1.5.5
      - idna==3.11
      - imageio==2.35.1
      - importlib-resources==6.4.5
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - kornia==0.7.3
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - medmnist==3.0.2
      - mpmath==1.3.0
      - networkx==3.1
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.20.5
      - nvidia-nvtx-cu11==11.8.86
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - pot==0.9.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - requests==2.32.4
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - sympy==1.13.3
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - torch==2.4.1+cu118
      - torchaudio==2.4.1+cu118
      - torchvision==0.19.1+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - triton==3.0.0
      - ttach==0.0.3
      - tzdata==2025.3
      - urllib3==2.2.3
      - visdom==0.2.4
      - websocket-client==1.8.0
      - zipp==3.20.2