exp_name: "CIFAR100_DWA"
dataset:
  data_name: "CIFAR100"
  root_path: 'H:/codes/dataset'
  train_batch_size: 512
  test_batch_size: 256
  channels: 3
  num_classes: 100
  image_size: 32

distribution:
  type: "dirichlet"
  label_num_per_client: 2
  alpha: 0.05

client:
  num_clients: 5

server:
  num_rounds: 100
  frac_clients: 1.0
  lr: 0.05
  local_epochs: 10
  optimizer: "sgd"
  momentum: 0.9
  weight_decay: 0.0001
  loss_name: "ce"
  model_name: "resnet18"
  aggregated_by_datasize: True
  lr_decay_per_round: 0.998

device: "cuda:0"

checkpoint:
  save_path: "./checkpoints/dwa"
  save_freq: 10
  result_file: "results.yaml"

pretrain:
  model_name: "resnet18"

etf:
  loss_name: "ce"
visualization:
  interval: 5
  save_path: 'visualization/dwa'
  vis_size: 16
resume: False
seed: 1

lambda_align_initial: 5.0 # Initial baseline
lambda_scheduler: dwa
